import { EngineeringTicket } from "./ticket-types";

export const SPRINT_1_TICKETS: EngineeringTicket[] = [
  {
    id: "BEL-101",
    title: "Design Wireframe ATS Diagnostics & Bot-Eye Dual Screen",
    description: "Thiết kế giao diện Split-pane (45% chẩn đoán, 55% preview) chuẩn Bloomberg Terminal.",
    assignee: "@des-lead",
    sprint: 1,
    priority: "P0",
    points: 3,
    status: "DONE",
    acceptanceCriteria: ["Bố cục Split-pane 45/55", "Bảng màu cảnh báo semantic", "Chế độ Bot-Eye Monospace"],
    liveUrl: "/ats-diagnostics",
  },
  {
    id: "BEL-102",
    title: "DB Schema & Models: job_descriptions, resume_jd_matches",
    description: "Khởi tạo bảng PostgreSQL lưu trữ JD và kết quả quét ATS với JSONB index.",
    assignee: "@be-senior",
    sprint: 1,
    priority: "P0",
    points: 3,
    status: "DONE",
    acceptanceCriteria: ["Alembic migration sạch", "Index GIN trên skills_extracted", "Cascade delete identity"],
    evidenceCommand: "pytest backend/tests/test_ats_matching.py",
  },
  {
    id: "BEL-103",
    title: "Backend ATS Match Engine Sub-50ms Heuristic",
    description: "Endpoint POST /v1/match/ats-scan so khớp từ khóa và tính điểm ATS không tốn token LLM.",
    assignee: "@be-senior",
    sprint: 1,
    priority: "P0",
    points: 5,
    status: "DONE",
    acceptanceCriteria: ["Bóc tách kỹ năng < 50ms", "Tính điểm 0-100", "Bắt lỗi file > 5MB mã 413"],
    liveUrl: "/ats-diagnostics",
  },
  {
    id: "BEL-104",
    title: "Frontend Split-Pane ATS Diagnostics Workspace",
    description: "Giao diện song song Visual PDF vs Bot-Eye Raw Text với scorecard chi tiết.",
    assignee: "@fe-lead",
    sprint: 1,
    priority: "P0",
    points: 5,
    status: "DONE",
    acceptanceCriteria: ["100vh Zero Dead-Space", "Chuyển chế độ mượt mà", "Nạp nhanh mẫu Shopee/VNG"],
    liveUrl: "/ats-diagnostics",
  },
  {
    id: "BEL-105",
    title: "Playwright E2E Suite cho ATS Diagnostics",
    description: "Bộ kiểm thử tự động toàn diện luồng quét và xem Bot-Eye trên 4 trình duyệt.",
    assignee: "@qc-lead",
    sprint: 1,
    priority: "P0",
    points: 5,
    status: "DONE",
    acceptanceCriteria: ["16/16 test cases pass", "Test toggle Bot-Eye", "Test modal flex card"],
    evidenceCommand: "bun run test tests/e2e/ats-diagnostics.spec.ts",
  },
  {
    id: "BEL-106",
    title: "DB Schema: candidate_job_applications_tracker",
    description: "Bảng lưu trữ hồ sơ ứng tuyển theo dõi 5 trạng thái Kanban.",
    assignee: "@be-senior",
    sprint: 1,
    priority: "P0",
    points: 3,
    status: "DONE",
    acceptanceCriteria: ["31 bảng trong DB", "Index candidate_id + status", "Khóa ngoại cascade"],
    evidenceCommand: "pytest backend/tests/test_job_tracker.py",
  },
  {
    id: "BEL-107",
    title: "Backend CRUD API: /v1/tracker/jobs/ với IDOR Guard",
    description: "Endpoint quản lý trạng thái nộp đơn, lương kỳ vọng, bảo mật phân quyền người dùng.",
    assignee: "@be-senior",
    sprint: 1,
    priority: "P0",
    points: 5,
    status: "DONE",
    acceptanceCriteria: ["GET/POST/PATCH/DELETE đầy đủ", "Chặn IDOR tuyệt đối", "Commit DB mutation"],
    liveUrl: "/workspace/jobs",
  },
  {
    id: "BEL-108",
    title: "Frontend UI: Job Application Kanban Board",
    description: "Bàn làm việc theo dõi 5 cột Kanban: Targeting -> Tailored -> Applied -> Interview -> Offer.",
    assignee: "@fe-lead",
    sprint: 1,
    priority: "P0",
    points: 5,
    status: "DONE",
    acceptanceCriteria: ["5 cột Kanban chuẩn IT", "Lọc công ty/vị trí tức thì", "Modal tạo công việc nhanh"],
    liveUrl: "/workspace/jobs",
  },
  {
    id: "BEL-109",
    title: "Playwright E2E Suite cho Job Kanban Tracker",
    description: "Kiểm thử tự động các thao tác kéo thả, tìm kiếm và tạo mới công việc.",
    assignee: "@qc-lead",
    sprint: 1,
    priority: "P0",
    points: 5,
    status: "DONE",
    acceptanceCriteria: ["12/12 test cases pass", "Kiểm thử modal thêm việc", "Kiểm thử filter"],
    evidenceCommand: "bun run test tests/e2e/job-tracker-kanban.spec.ts",
  },
  {
    id: "BEL-110",
    title: "Design Pro CV Studio 3-Column Zero Dead-Space",
    description: "Bố cục 3:4:5 cột (Cấu trúc - Soạn thảo STAR - A4 Preview).",
    assignee: "@des-lead",
    sprint: 1,
    priority: "P0",
    points: 3,
    status: "DONE",
    acceptanceCriteria: ["Tỉ lệ 3:4:5 chuẩn", "Thanh slider margin 0.5-1.0in", "Thước đo khít trang A4"],
    liveUrl: "/cv-studio",
  },
  {
    id: "BEL-111",
    title: "Frontend Workspace: Pro CV Studio & Dynamic Adjuster",
    description: "Trình biên tập form STAR định lượng và xem trước giấy A4 vector precision.",
    assignee: "@fe-lead",
    sprint: 1,
    priority: "P0",
    points: 8,
    status: "DONE",
    acceptanceCriteria: ["Slider cỡ chữ/khoảng cách/lề", "Nút Snap 1-Page A4", "Biên tập STAR realtime"],
    liveUrl: "/cv-studio",
  },
  {
    id: "BEL-112",
    title: "Playwright E2E Suite cho Pro CV Studio",
    description: "Kiểm thử tương tác nhập liệu form STAR và thuật toán tối ưu lề trang.",
    assignee: "@qc-lead",
    sprint: 1,
    priority: "P0",
    points: 5,
    status: "DONE",
    acceptanceCriteria: ["12/12 test cases pass", "Test auto-fit margin", "Test STAR sync"],
    evidenceCommand: "bun run test tests/e2e/cv-studio.spec.ts",
  },
];
