import { EngineeringTicket } from "./ticket-types";

export const SPRINT_2_3_4_TICKETS: EngineeringTicket[] = [
  // Sprint 2 (Monetization & Viral Growth)
  {
    id: "BEL-201",
    title: "Design Specs: MoMo QR Dialog & Gói Cước 29k/59k",
    description: "Modal thanh toán quét mã QR chuẩn nhận diện MoMo với bộ đếm ngược 10 phút.",
    assignee: "@des-lead",
    sprint: 2,
    priority: "P0",
    points: 2,
    status: "IN_PROGRESS",
    acceptanceCriteria: ["Thương hiệu MoMo chính thống", "Đếm ngược 10 phút", "Hiển thị rõ mã đơn"],
  },
  {
    id: "BEL-202",
    title: "Backend MoMo Merchant V2 API (POST /v1/payments/momo/create-qr)",
    description: "Sinh mã QR thanh toán động với chữ ký số HMAC-SHA256, ghi nhận đơn hàng PENDING.",
    assignee: "@be-senior",
    sprint: 2,
    priority: "P0",
    points: 5,
    status: "IN_PROGRESS",
    acceptanceCriteria: ["Ký số HMAC chuẩn MoMo v2", "Sinh payUrl trong < 300ms", "Lưu Order PENDING"],
  },
  {
    id: "BEL-203",
    title: "Backend MoMo IPN Webhook với Khóa Idempotency",
    description: "Tiếp nhận kết quả IPN, SELECT FOR UPDATE chống race condition, cộng lượt quét.",
    assignee: "@be-senior",
    sprint: 2,
    priority: "P0",
    points: 5,
    status: "IN_PROGRESS",
    acceptanceCriteria: ["Kiểm tra HMAC signature", "Row-level lock chống double-charge", "Cập nhật lượt scan"],
  },
  {
    id: "BEL-204",
    title: "Frontend MoMo Payment Dialog & Realtime Status Polling",
    description: "Component popup hiển thị mã QR MoMo, polling trạng thái thanh toán tự động.",
    assignee: "@fe-lead",
    sprint: 2,
    priority: "P0",
    points: 3,
    status: "IN_PROGRESS",
    acceptanceCriteria: ["Polling mỗi 2 giây", "Tự động nhảy thành công", "Đóng mở mượt mà"],
  },
  {
    id: "BEL-205",
    title: "QC Suite: Giả Lập Webhook MoMo & Stress Test Idempotency",
    description: "Bắn 10 request IPN đồng thời để kiểm tra cơ chế chống thanh toán trùng lặp.",
    assignee: "@qc-lead",
    sprint: 2,
    priority: "P0",
    points: 5,
    status: "TODO",
    acceptanceCriteria: ["Chỉ xử lý đúng 1 đơn", "Trả về 200 OK cho 9 đơn lặp", "Số dư chính xác"],
  },
  {
    id: "BEL-206",
    title: "Viral Loop: Roast My CV & Thẻ Bài ATS Cyberpunk Flex Điểm",
    description: "Modal sinh thẻ bài Neon 1200x630, huy hiệu danh hiệu, câu roast châm biếm, 1-click share LinkedIn.",
    assignee: "@fe-lead",
    sprint: 2,
    priority: "P0",
    points: 5,
    status: "DONE",
    acceptanceCriteria: ["Thẻ bài Cyberpunk 1200x630", "Rank badge tự động", "Nút copy link ref & share LinkedIn"],
    liveUrl: "/ats-diagnostics",
  },
  {
    id: "BEL-207",
    title: "Market Radar: Tra Cứu Lương IT & Radar Kỹ Năng (/salary-benchmark)",
    description: "Báo cáo trung vị lương P25 - P50 - P75 theo ngôn ngữ + kinh nghiệm, Top 5 skill kéo lương.",
    assignee: "@fe-lead",
    sprint: 2,
    priority: "P0",
    points: 5,
    status: "DONE",
    acceptanceCriteria: ["Dải lương P25/P50/P75 trực quan", "Top 5 kỹ năng giá trị cao", "16 Playwright tests pass"],
    liveUrl: "/salary-benchmark",
  },
  {
    id: "BEL-208",
    title: "Product Stickiness: AI Mock Interview Q&A Generator",
    description: "Tự sinh 10 câu hỏi phỏng vấn kỹ thuật và barem chấm điểm bám sát JD & CV.",
    assignee: "@be-senior",
    sprint: 2,
    priority: "P1",
    points: 5,
    status: "IN_PROGRESS",
    acceptanceCriteria: ["Trích xuất 5 hard skills", "Sinh câu hỏi System Design & Lý thuyết", "Barem chấm điểm"],
  },
  {
    id: "BEL-209",
    title: "Data Cold-Start: JD Crawler & Skill Ingestion Worker",
    description: "Worker cào tự động 3,000+ JD IT công khai từ thị trường để chuẩn hóa taxonomy.",
    assignee: "@be-senior",
    sprint: 2,
    priority: "P0",
    points: 5,
    status: "TODO",
    acceptanceCriteria: ["Cào 3,000+ JD IT sạch", "Bóc tách kỹ năng vào catalog", "Không vi phạm robots.txt"],
  },

  // Sprint 3 (Expert Review & Escrow)
  {
    id: "BEL-301",
    title: "Design: Figma-Style CV Inline Annotation & Tags",
    description: "UI bóng comment bôi đen text, Quick-tags #NeedMetric, #Vague, đồng hồ SLA.",
    assignee: "@des-lead",
    sprint: 3,
    priority: "P0",
    points: 3,
    status: "TODO",
    acceptanceCriteria: ["Floating comment bubble", "Quick tags chọn nhanh", "Header đếm ngược SLA"],
  },
  {
    id: "BEL-302",
    title: "Backend: Sổ Cái escrow_ledger & Trừ Phí Sàn 8%",
    description: "Tự động chia tiền 8% về ví sàn Belooga, 92% giữ trong Escrow cho Chuyên gia.",
    assignee: "@be-senior",
    sprint: 3,
    priority: "P0",
    points: 5,
    status: "TODO",
    acceptanceCriteria: ["Chia đúng 8% / 92%", "Kiểm tra tối thiểu 3 comment", "Bảo vệ IDOR"],
  },
  {
    id: "BEL-303",
    title: "Backend: Gom Đợt Rút Tiền Batch Payout & Thuế TNCN 10%",
    description: "Quản lý lệnh rút tiền về MoMo cá nhân của Chuyên gia, khấu trừ thuế TNCN khi > 2 triệu.",
    assignee: "@be-senior",
    sprint: 3,
    priority: "P1",
    points: 5,
    status: "TODO",
    acceptanceCriteria: ["Chặn rút dưới 500k", "Khấu trừ 10% thuế TNCN khi > 2tr", "Lưu log kiểm toán"],
  },
  {
    id: "BEL-304",
    title: "Frontend Workspace: Expert Review Studio (/expert/studio/[id])",
    description: "Không gian làm việc cho Chuyên gia chấm bài inline, thanh SLA đếm ngược, AI Copilot.",
    assignee: "@fe-lead",
    sprint: 3,
    priority: "P0",
    points: 8,
    status: "TODO",
    acceptanceCriteria: ["Bôi đen chữ thả comment", "Barem 3 tiêu chuẩn chấm", "AI Copilot gợi ý"],
  },
  {
    id: "BEL-305",
    title: "Frontend UI: Expert Wallet & Lịch Sử Thu Nhập",
    description: "Màn hình quản lý số dư khả dụng, quỹ tạm giữ Escrow, lệnh rút tiền MoMo.",
    assignee: "@fe-lead",
    sprint: 3,
    priority: "P1",
    points: 3,
    status: "TODO",
    acceptanceCriteria: ["Hiển thị 3 thẻ số dư", "Form rút tiền MoMo", "Cảnh báo thuế minh bạch"],
  },
  {
    id: "BEL-306",
    title: "QC E2E: Toàn Chu Trình Đặt Hàng -> Chấm Bài -> Rút Tiền",
    description: "Kịch bản Playwright full chu trình từ ứng viên đặt review tới Chuyên gia rút tiền.",
    assignee: "@qc-lead",
    sprint: 3,
    priority: "P0",
    points: 5,
    status: "TODO",
    acceptanceCriteria: ["Full flow E2E pass", "Kiểm tra số dư nhảy tự động", "Bảo vệ tiền Escrow"],
  },

  // Sprint 4 (Executive & Production)
  {
    id: "BEL-401",
    title: "Backend Analytics Engine: Realtime GMV & Escrow Float",
    description: "API /v1/analytics/dashboard tổng hợp GMV, doanh thu ròng, quỹ Escrow trong < 50ms.",
    assignee: "@be-senior",
    sprint: 4,
    priority: "P0",
    points: 5,
    status: "DONE",
    acceptanceCriteria: ["Doanh thu ròng sàn", "P&L waterfall", "Pytest pass 100%"],
    evidenceCommand: "pytest backend/tests/test_analytics.py",
  },
  {
    id: "BEL-402",
    title: "Frontend: Executive Financial Terminal (/admin/analytics)",
    description: "Bảng điều hành Bloomberg, 6 thẻ KPI, Bar Chart 7D, Funnel chuyển đổi tự nguyện.",
    assignee: "@fe-lead",
    sprint: 4,
    priority: "P0",
    points: 5,
    status: "DONE",
    acceptanceCriteria: ["6 thẻ KPI", "Biểu đồ cột 7D", "Phễu PLG", "16 Playwright tests pass"],
    liveUrl: "/admin/analytics",
  },
  {
    id: "BEL-403",
    title: "DevOps & SecOps: Nginx Reverse Proxy, SSL, Turnstile & 5MB Limit",
    description: "Cấu hình Docker Compose, Nginx chặn request > 5MB, Cloudflare Turnstile chống bot.",
    assignee: "@ops-lead",
    sprint: 4,
    priority: "P0",
    points: 5,
    status: "TODO",
    acceptanceCriteria: ["Giới hạn 5MB upload", "VPS RAM < 2.5GB", "Chi phí < $15/tháng"],
  },
  {
    id: "BEL-404",
    title: "QC Audit Gate: Full Regression Suite & Verification DoD",
    description: "Chạy toàn bộ Pytest + E2E Playwright + audit-truth.sh pass 8 cổng 100%.",
    assignee: "@qc-lead",
    sprint: 4,
    priority: "P0",
    points: 8,
    status: "TODO",
    acceptanceCriteria: ["Coverage > 85%", "audit-truth.sh pass 8/8", "Zero IDOR violations"],
  },
];
